name: Smart Contract Deployment

on:
  pull_request:
jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    env:
      CARGO_TERM_COLOR: always
      DEPLOYER_SECRET: ${{ secrets.DEPLOYER_SECRET }}
    steps:
      - uses: actions/checkout@v3
      # - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      # - run: rustup target add wasm32-unknown-unknown
      # - name: Contract Build
      #   run: |
      #     cd mtk-automation
      #     cargo build --target wasm32-unknown-unknown --release
      # - name: Code Tests
      #   run: |
      #     cd mtk-automation
      #     cargo test
      # - run: cargo install --locked --version 0.6.0 soroban-cli
      # - name: Contract Deployment to futurenet
      - run: echo ${{ secrets.DEPLOYER_SECRET }}
        # run: |
        #   cd mtk-automation
        #   soroban contract deploy \
        #   --wasm target/wasm32-unknown-unknown/release/mtk_automation.wasm \
        #   --secret-key "$DEPLOYER_SECRET" \
        #   --rpc-url https://horizon-futurenet.stellar.cash:443/soroban/rpc \
        #   --network-passphrase 'Test SDF Future Network ; October 2022'
